Repository TU-NEBULA/nebula-backend, pull requests merged in 2025-02, with the labels that each got.

#11 scrum 126 : 스타 생성 + 전체 및 단일 조회 기능 구현
  build.gradle
  src/main/java/com/team_nebula/nebula/domain/category/api/CategoryController.java
  src/main/java/com/team_nebula/nebula/domain/category/entity/Category.java
  src/main/java/com/team_nebula/nebula/domain/category/repository/CategoryRepository.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandService.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/image/S3Service.java
  src/main/java/com/team_nebula/nebula/domain/keyword/entity/Keyword.java
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandService.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/link/entity/Link.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkCommandService.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkQueryService.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/converter/StarConverter.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/CreateStarFileDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/CreateStarRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/CreateStarResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetLinkOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetStarListResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetStarOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/entity/Star.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarReapository.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/team_nebula/nebula/global/config/S3Config.java
Labels: Feature

#12 scrum 130 : 키워드별, 카테고리별 스타 조회 기능 구현
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkQueryService.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetStarListResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
Labels: Feature

#13 SCRUM-138: AuthUser로 API 유저 인증 구현
  src/main/java/com/team_nebula/nebula/domain/category/api/CategoryController.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/request/CreateCategoryRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandService.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
Labels: Feature

#14 scrum 137 : 스타 검색 기능 구현
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/converter/StarConverter.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
Labels: Feature

#15 CICD(SCRUM-112): Create cd-dev.yml
  .github/workflows/cd-dev.yml
Labels: CI/CD

#16 fix(SCRUM-112): cd-dev.yml 컨테이너 명 없어 발생하는 에러 무시
  .github/workflows/cd-dev.yml
Labels: CI/CD

#19 fix(SCRUM-112): cd-dev.yml 컨테이너 명 없어 발생하는 에러 우회
  .github/workflows/cd-dev.yml
Labels: CI/CD

#20 fix(SCRUM-112): cd-dev.yml DOCKER_REPO name 적용
  .github/workflows/cd-dev.yml
Labels: CI/CD

#22 SCRUM 141 : 스타 생성 API 에러 수정
  src/main/java/com/team_nebula/nebula/domain/image/S3Service.java
  src/main/java/com/team_nebula/nebula/domain/keyword/entity/Keyword.java
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/link/entity/Link.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkQueryService.java
  src/main/java/com/team_nebula/nebula/domain/link/service/LinkQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/converter/StarConverter.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/CreateStarRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/CreateStarResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetLinkOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetStarOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/entity/Star.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
Labels: Bug

#24 SCRUM-149 : 소셜 로그인 리다이렉트 수정
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
Labels: Feature

#27 SCRUM 146 : 카테고리 수정 및 삭제 기능 구현
  src/main/java/com/team_nebula/nebula/domain/category/api/CategoryController.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/request/UpdateCategoryOneRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/response/DeleteCategoryResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/response/UpdateCategoryOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/entity/Category.java
  src/main/java/com/team_nebula/nebula/domain/category/repository/CategoryRepository.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandService.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
Labels: Feature, Refactor

#31 SCRUM152 : 스타 생성 취소 기능 구현 + 스타 조회 기능 수정
  src/main/java/com/team_nebula/nebula/domain/category/api/CategoryController.java
  src/main/java/com/team_nebula/nebula/domain/image/S3Service.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/converter/StarConverter.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/CreateStarRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/entity/Star.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
Labels: Feature, Refactor

#32 SCRUM 158 : 스타 정보 수정 기능 Refactor + 고립 키워드 노드 삭제 기능 구현
  src/main/java/com/team_nebula/nebula/domain/keyword/api/KeywordController.java
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandService.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/UpdateStarOneRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
Labels: Feature, Refactor

#33 SCRUM143 : LogBack 설정 및 Cors 설정
  .gitignore
  build.gradle
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
  src/main/resources/logback-spring.xml
Labels: Feature

#34 SCRUM-143: 임시 토큰 발급 로직 구현
  .gitignore
  elk/.env
  elk/docker-compose.yml
  elk/elasticsearch/.dockerignore
  elk/elasticsearch/Dockerfile
  elk/elasticsearch/config/elasticsearch.yml
  elk/kibana/.dockerignore
  elk/kibana/Dockerfile
  elk/kibana/config/kibana.yml
  elk/logstash/.dockerignore
  elk/logstash/Dockerfile
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/logstash.conf
  src/main/java/com/team_nebula/nebula/global/oauth/api/OAuthController.java
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
  src/main/resources/logback-spring.xml
Labels: Feature

#36 SCRUM-143: Cors 설정 변경 / Swagger 서버 분리
  src/main/java/com/team_nebula/nebula/global/config/CorsMvcConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
Labels: Refactor
