Repository TU-NEBULA/nebula-backend, pull requests merged in 2025-01, with the labels that each got.

#1 feat(SCRUM-115): API 응답 통일 구현
  src/main/java/com/team_nebula/nebula/global/apipayload/ApiResponse.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/BaseErrorCode.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/ErrorReasonDto.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/SuccessStatus.java
  src/main/java/com/team_nebula/nebula/global/apipayload/exception/ExceptionAdvice.java
  src/main/java/com/team_nebula/nebula/global/apipayload/exception/GeneralException.java
Labels: Feature

#2 SCRUM-109: 소셜 로그인(카카오, 구글) 구현
  build.gradle
  src/main/java/com/team_nebula/nebula/domain/oauth/dto/CustomOAuth2User.java
  src/main/java/com/team_nebula/nebula/domain/oauth/dto/GoogleResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/oauth/dto/KakaoResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/oauth/dto/OAuth2Response.java
  src/main/java/com/team_nebula/nebula/domain/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/team_nebula/nebula/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/team_nebula/nebula/domain/user/dto/request/UserDTO.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/User.java
  src/main/java/com/team_nebula/nebula/domain/user/repository/UserRepository.java
  src/main/java/com/team_nebula/nebula/global/config/CorsMvcConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
  src/main/java/com/team_nebula/nebula/global/util/JWTFilter.java
  src/main/java/com/team_nebula/nebula/global/util/JWTUtil.java
Labels: Feature

#3 SCRUM 118 : 도메인 노드 세팅 및 Neo4j, MySQL Config 구현
  src/main/java/com/team_nebula/nebula/domain/category/entity/Category.java
  src/main/java/com/team_nebula/nebula/domain/category/repository/CategoryRepository.java
  src/main/java/com/team_nebula/nebula/domain/common/BaseEntity.java
  src/main/java/com/team_nebula/nebula/domain/keyword/entity/Keyword.java
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/link/entity/Link.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/team_nebula/nebula/domain/star/entity/Star.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarReapository.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/UserNode.java
  src/main/java/com/team_nebula/nebula/domain/user/repository/mysql/UserRepository.java
  src/main/java/com/team_nebula/nebula/domain/user/repository/neo4j/UserNodeRepository.java
  src/main/java/com/team_nebula/nebula/global/config/MySQLConfig.java
  src/main/java/com/team_nebula/nebula/global/config/Neo4jConfig.java
Labels: Chore

#6 SCRUM-125: Create ci-dev.yml
  .github/workflows/ci-dev.yml
Labels: CI/CD

#8 SCRUM-135: h2 데이터베이스 설정
  build.gradle
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
Labels: Database

#7 SCRUM-127 : 카테고리 생성 및 전체 조회 기능 구현
  src/main/java/com/team_nebula/nebula/domain/category/api/CategoryController.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/request/CreateCategoryRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/response/CreateCategoryResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/response/GetCategoryListResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/dto/response/GetCategoryOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/category/repository/CategoryRepository.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandService.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryQueryService.java
  src/main/java/com/team_nebula/nebula/domain/category/service/CategoryQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/UserNode.java
  src/main/java/com/team_nebula/nebula/domain/user/repository/neo4j/UserNodeRepository.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
Labels: Feature

#5 SCRUM-120: reissue 구현
  src/main/java/com/team_nebula/nebula/domain/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/team_nebula/nebula/domain/user/dto/request/UserDTO.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/User.java
  src/main/java/com/team_nebula/nebula/domain/user/repository/mysql/UserRepository.java
  src/main/java/com/team_nebula/nebula/global/annotation/AuthUser.java
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
  src/main/java/com/team_nebula/nebula/global/config/WebMVCConfig.java
  src/main/java/com/team_nebula/nebula/global/oauth/api/OAuthController.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/CustomOAuth2User.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/GoogleResponseDTO.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/KakaoResponseDTO.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/OAuth2Response.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/TokenResponseDTO.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/team_nebula/nebula/global/util/AuthArgumentResolver.java
  src/main/java/com/team_nebula/nebula/global/util/JWTFilter.java
  src/main/java/com/team_nebula/nebula/global/util/JWTUtil.java
Labels: Feature

#10 SCRUM-122: 초기 로그인 시 유저 노드 생성
  src/main/java/com/team_nebula/nebula/domain/user/entity/UserNode.java
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
Labels: Feature
