Repository TU-NEBULA/nebula-backend, pull requests merged in 2025-03, with the labels that each got.

#37 SCRUM-143: ELK docker-compose.yml 수정
  elk/docker-compose.yml
  src/main/java/com/team_nebula/nebula/domain/user/entity/User.java
  src/main/java/com/team_nebula/nebula/global/config/CorsMvcConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
Labels: Refactor

#38 SCRUM 161 : 키워드 전체 조회 기능 구현
  .gitignore
  src/main/java/com/team_nebula/nebula/domain/keyword/api/KeywordController.java
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordQueryService.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/keywordQueryServiceImpl.java
Labels: Feature

#39 SCRUM-160: CI에 ELK .env 주입 추가
  .github/workflows/ci-dev.yml
  .github/workflows/ci-main.yml
Labels: CI/CD

#41 CICD(SCRUM-170): EC2로 배포 수정
  .github/workflows/cd-dev.yml
Labels: CI/CD

#40 SCRUM-166: 소셜 로그인 리펙토링
  src/main/java/com/team_nebula/nebula/domain/category/entity/Category.java
  src/main/java/com/team_nebula/nebula/domain/keyword/entity/Keyword.java
  src/main/java/com/team_nebula/nebula/domain/link/entity/Link.java
  src/main/java/com/team_nebula/nebula/domain/star/entity/Star.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/user/dto/request/UserDTO.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/User.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/UserNode.java
  src/main/java/com/team_nebula/nebula/global/AI/dto/GetThumbnailAndKeywordsResponseDTO.java
  src/main/java/com/team_nebula/nebula/global/AI/service/AiService.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/team_nebula/nebula/global/common/BaseEntity.java
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
  src/main/java/com/team_nebula/nebula/global/config/WebMVCConfig.java
  src/main/java/com/team_nebula/nebula/global/constants/Constants.java
  src/main/java/com/team_nebula/nebula/global/image/S3Service.java
  src/main/java/com/team_nebula/nebula/global/interceptor/pre/AuthUserArgumentResolver.java
  src/main/java/com/team_nebula/nebula/global/interceptor/pre/JWTInterceptor.java
  src/main/java/com/team_nebula/nebula/global/oauth/api/OAuthController.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/CustomOAuth2User.java
  src/main/java/com/team_nebula/nebula/global/oauth/dto/TokenResponseDTO.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomFailureHandler.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/team_nebula/nebula/global/util/AuthArgumentResolver.java
  src/main/java/com/team_nebula/nebula/global/util/ErrorResponseUtil.java
  src/main/java/com/team_nebula/nebula/global/util/JWTFilter.java
  src/main/java/com/team_nebula/nebula/global/util/JWTUtil.java
Labels: Refactor

#42 SCRUM-166: Swaggerconfig 수정
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
Labels: Refactor

#43 SCRUM-166: tokenType명 수정
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
Labels: Refactor

#46 SCRUM-166: 익스텐션, 웹 리다이렉트 수정
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
Labels: Refactor

#47 SCRUM-166: 소셜 로그인 컨트롤러로 수정
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
  src/main/java/com/team_nebula/nebula/global/config/SwaggerConfig.java
  src/main/java/com/team_nebula/nebula/global/constants/Constants.java
  src/main/java/com/team_nebula/nebula/global/oauth/api/OAuthController.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
Labels: Refactor

#48 SCRUM-166: 로그인 리다이렉트 시 쿼리 파라미터로 토큰 응답
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
Labels: Refactor

#49 SCRUM-166: 쿠키 만료 시간 설정
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/team_nebula/nebula/global/util/JWTUtil.java
Labels: Refactor

#50 SCRUM-173: @AuthUser Long 타입으로 받도록 수정
  src/main/java/com/team_nebula/nebula/domain/category/api/CategoryController.java
  src/main/java/com/team_nebula/nebula/domain/keyword/api/KeywordController.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordQueryService.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/keywordQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
Labels: Refactor

#52 SCRUM-174: Security PATCH 메서드 허용
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
Labels: Bug

#53 SCRUM -169 : 유저 스타 작업 체크 기능 구현
  build.gradle
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordQueryService.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/keywordQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/api/StarController.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/user/entity/UserNode.java
  src/main/java/com/team_nebula/nebula/global/AI/service/AiService.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/team_nebula/nebula/global/config/AsyncConfig.java
  src/main/java/com/team_nebula/nebula/global/config/WebClientConfig.java
Labels: Feature, Refactor

#51 SCRUM-172: 이용약관 API 구현
  src/main/java/com/team_nebula/nebula/domain/term/api/TermController.java
  src/main/java/com/team_nebula/nebula/domain/term/converter/TermConverter.java
  src/main/java/com/team_nebula/nebula/domain/term/dto/request/AgreeTermRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/term/dto/request/TermRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/term/dto/response/TermResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/term/entity/Term.java
  src/main/java/com/team_nebula/nebula/domain/term/entity/TermType.java
  src/main/java/com/team_nebula/nebula/domain/term/entity/UserTerm.java
  src/main/java/com/team_nebula/nebula/domain/term/entity/UserTermId.java
  src/main/java/com/team_nebula/nebula/domain/term/repository/TermRepository.java
  src/main/java/com/team_nebula/nebula/domain/term/repository/UserTermRepository.java
  src/main/java/com/team_nebula/nebula/domain/term/service/TermService.java
  src/main/java/com/team_nebula/nebula/domain/term/service/TermServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
  src/main/java/com/team_nebula/nebula/global/config/MySQLConfig.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
Labels: Feature

#55 SCRUM 176 : 스타 수정 최신화 오류 및 스타 삭제 후 링크 조회 오류 수정
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/keyword/service/KeywordCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/UpdateStarOneRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
Labels: Bug

#56 fix(SCRUM-176) : 스타 제목,메모,AI요약 수정 오류 해결
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
Labels: Bug

#57 Revert "fix(SCRUM-176) : 스타 제목,메모,AI요약 수정 오류 해결"
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
Labels: Bug

#59 Revert "Revert "fix(SCRUM-176) : 스타 제목,메모,AI요약 수정 오류 해결""
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
Labels: Chore

#63 SCRUM-182: 유저 정보 조회 API 구현
  src/main/java/com/team_nebula/nebula/domain/user/api/UserController.java
  src/main/java/com/team_nebula/nebula/domain/user/converter/UserConverter.java
  src/main/java/com/team_nebula/nebula/domain/user/dto/response/UserResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/user/service/UserService.java
  src/main/java/com/team_nebula/nebula/domain/user/service/UserServiceImpl.java
Labels: Feature
