Repository TU-NEBULA/nebula-backend, pull requests merged in 2025-05, with the labels that each got.

#65 SCURM 187 : 링크 노드에 공유 키워드 리스트 추가 및 기능 수정
  src/main/java/com/team_nebula/nebula/domain/link/converter/LinkConverter.java
  src/main/java/com/team_nebula/nebula/domain/link/entity/Link.java
  src/main/java/com/team_nebula/nebula/domain/link/repository/LinkRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/GetLinkOneResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
Labels: Refactor

#67 SCRUM-189: CI/CD 통합
  .github/workflows/cd-dev.yml
  .github/workflows/ci-dev.yml
Labels: CI/CD

#68 SCRUM-184: 소셜 로그인 헤더 검증에서 쿠키 자체 검증으로 수정
  src/main/java/com/team_nebula/nebula/global/constants/Constants.java
  src/main/java/com/team_nebula/nebula/global/oauth/api/OAuthController.java
  src/main/java/com/team_nebula/nebula/global/oauth/handler/CustomSuccessHandler.java
  src/main/java/com/team_nebula/nebula/global/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/team_nebula/nebula/global/util/CookieUtil.java
  src/main/java/com/team_nebula/nebula/global/util/JWTFilter.java
  src/main/java/com/team_nebula/nebula/global/util/JWTUtil.java
Labels: Refactor

#66 SCRUM-185: 방문기록 생성, 전체 조회 API 구현
  src/main/java/com/team_nebula/nebula/domain/history/api/HistoryController.java
  src/main/java/com/team_nebula/nebula/domain/history/converter/HistoryConverter.java
  src/main/java/com/team_nebula/nebula/domain/history/dto/request/CreateHistoryRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/history/dto/response/GetHistoryListResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/history/entity/History.java
  src/main/java/com/team_nebula/nebula/domain/history/repository/HistoryRepository.java
  src/main/java/com/team_nebula/nebula/domain/history/service/HistoryCommandService.java
  src/main/java/com/team_nebula/nebula/domain/history/service/HistoryCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/history/service/HistoryQueryService.java
  src/main/java/com/team_nebula/nebula/domain/history/service/HistoryQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/repository/StarRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryService.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/user/api/UserController.java
  src/main/java/com/team_nebula/nebula/domain/user/service/UserQueryService.java
  src/main/java/com/team_nebula/nebula/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/config/MySQLConfig.java
Labels: Feature

#69 SCRUM-195: 쿠키 도메인 설정
  src/main/java/com/team_nebula/nebula/global/util/CookieUtil.java
Labels: Bug

#70 SCRUM-195: 쿠키 도메인 제거
  src/main/java/com/team_nebula/nebula/global/util/CookieUtil.java
Labels: Bug

#71 SCRUM-199: Cors allow origin 설정
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
Labels: Bug

#73 SCRUM-199: Cors allow origin 설정
  src/main/java/com/team_nebula/nebula/global/config/SecurityConfig.java
Labels: Bug

#74 SCRUM-199: SameSite 적용
  src/main/java/com/team_nebula/nebula/global/util/CookieUtil.java
Labels: Bug

#75 SCRUM-199: SameSite 제거
  src/main/java/com/team_nebula/nebula/global/util/CookieUtil.java
Labels: Bug

#77 SCRUM-202 : 방문기록 전체 조회시 pagiNation 구현
  src/main/java/com/team_nebula/nebula/domain/history/api/HistoryController.java
  src/main/java/com/team_nebula/nebula/domain/history/dto/response/GetHistoryListPageResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/history/service/HistoryQueryService.java
  src/main/java/com/team_nebula/nebula/domain/history/service/HistoryQueryServiceImpl.java
Labels: Feature

#78 SCRUM-203 : 방문기록 최신 정렬 조회로 수정
  src/main/java/com/team_nebula/nebula/domain/history/api/HistoryController.java
  src/main/java/com/team_nebula/nebula/domain/history/entity/History.java
Labels: Refactor

#80 SCRUM 208 : 스타 저장 후 AI 서버로 데이터전송 기능 추가
  src/main/java/com/team_nebula/nebula/domain/keyword/api/KeywordController.java
  src/main/java/com/team_nebula/nebula/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/request/CreateStarRequestDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/dto/response/AddBookMarkResponseDTO.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/AI/service/AiMessageService.java
  src/main/java/com/team_nebula/nebula/global/apipayload/code/status/ErrorStatus.java
Labels: Refactor

#81 SCRUM-204: 시나리오 1,2, 4 테스트 코드 작성
  src/main/java/com/team_nebula/nebula/domain/history/dto/request/CreateHistoryRequestDTO.java
  src/test/java/com/team_nebula/nebula/usecase/UsecaseTest.java
Labels: Test

#84 SCRUM 211 : tistory 파비콘 통일 및 S3 파일 url 에러 해결
  src/main/java/com/team_nebula/nebula/domain/favicon/service/FaviconServiceImpl.java
  src/main/java/com/team_nebula/nebula/domain/star/service/StarCommandServiceImpl.java
  src/main/java/com/team_nebula/nebula/global/image/S3Service.java
Labels: Bug
